project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: miketrizna.github.io
  title: "blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css



