project:
  type: website
  output-dir: docs

website:
  description: "Mike's personal website and blog"
  site-url: miketrizna.github.io
  title: "Open Mike"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/MikeTrizna/miketrizna.github.io
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



